server.port=9090
spring.mvc.throw-exception-if-no-handler-found=true

# Supabase PostgreSQL Database
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.xpsizzoswdcvdyjymtwo&password=kunal-htr%405476
spring.datasource.username=postgres.xpsizzoswdcvdyjymtwo
spring.datasource.password=kunal-htr%405476
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
