ALTER TABLE users ALTER COLUMN name TYPE VARCHAR(100);
UPDATE users SET name = 'Unknown' WHERE name IS NULL;
ALTER TABLE users ALTER COLUMN name SET DEFAULT 'Unknown';
ALTER TABLE users ALTER COLUMN name SET NOT NULL;
