package backend.dto;

/**
 * Per-file metadata describing a single submission's analysis characteristics.
 * <p>
 * Used to surface file-level statistics (token count, fingerprint count, size)
 * without exposing internal engine types.
 *
 * @param fileName         original file name of the submission
 * @param tokenCount       number of tokens produced by the tokenizer
 * @param fingerprintCount number of unique fingerprints generated by winnowing
 * @param fileSizeBytes    size of the original source content in bytes
 */
public record FileMetadataDTO(
        String fileName,
        int tokenCount,
        int fingerprintCount,
        long fileSizeBytes
) {}
